apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: artexplorer
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
    - path: /.*
      accessStrategies:
        - config: {}
          handler: noop
      methods:
        - GET
  service:
    host: art-explorer
    name: artexplorer
    port: 80