apiVersion: apps/v1
kind: Deployment
metadata:
  name: artexplorer
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: artexplorer
          image: ghcr.io/kyma-incubator/kymart/artexplorerfrontend:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: artexplorer-nginx-volume
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf             
          resources:
            limits:
              cpu: 0.5
              memory: 32Mi
            requests:
              cpu: 0.25
              memory: 8Mi              
      volumes:
        - name: artexplorer-nginx-volume
          configMap:
            name: artexplorer-nginx            