apiVersion: apps/v1
kind: Deployment
metadata:
  name: artexplorer
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: artexplorer
          image: kymart/artexplorerfrontend
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/nginx/html/config.js
              subPath: config.js
      volumes:
        - name: config-volume
          configMap:
            name: artexplorer