apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: artexplorer
  type: frontend
configMapGenerator:
  - name: artexplorer-nginx
    files:
    - ./config/nginx/default.conf  
resources:
  - deployment.yaml
  - service.yaml
  - apirule.yaml
  - autoscaler.yaml