apiVersion: v1
kind: Service
metadata:
  name: artexplorer
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
  selector:
    app: artexplorer
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: artexplorer
# spec:
#   type: LoadBalancer
#   loadBalancerIP: 35.240.99.35
#   ports:
#     - name: http
#       port: 80
#   selector:
#     app: artexplorer              