version: '3.5'
services:
  arttitleservice:
    image: ghcr.io/kyma-incubator/kymart/arttitleservice:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: 'arttitleservice'       
    restart: 'always'
    ports:
      - '8080:8080'