apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: arttitle
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
    - path: /.*
      accessStrategies:
        - config: {}
          handler: noop
      methods:
        - GET
  service:
    host: art-title
    name: arttitle
    port: 8080