apiVersion: apps/v1
kind: Deployment
metadata:
  name: arttitle
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: arttitle
          image: ghcr.io/kyma-incubator/kymart/arttitleservice:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          resources:
            limits:
              cpu: 3
              memory: 2.5Gi
            requests:
              cpu: 1
              memory: 1.5Gi             