apiVersion: serverless.kyma-project.io/v1alpha1
kind: Function
metadata:
  name: artlike
spec:
  buildResources:
    limits:
      cpu: 1100m
      memory: 1100Mi
    requests:
      cpu: 700m
      memory: 700Mi
  deps: |
    { 
      "name": "artlike",
      "version": "1.0.0",
      "dependencies":{}
    }
  maxReplicas: 1
  minReplicas: 1
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  runtime: nodejs12
  source: |
    module.exports = { 
        main: function (event, context) {
            console.log(event, context)
            return "Hello from ArtLike!";
            }
    }