version: '3.5'
services:
  artlikeservice:
    image: ghcr.io/kyma-incubator/kymart/artbackend:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: 'artbackend'       
    restart: 'always'
    ports:
      - '8081:80'
