apiVersion: apps/v1
kind: Deployment
metadata:
  name: artlike
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: artlike
          image: ghcr.io/kyma-incubator/kymart/artlikeservice:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: 64Mi
            requests:
              memory: 32Mi          
          ports:
            - name: http
              containerPort: 8080