apiVersion: apps/v1
kind: Deployment
metadata:
  name: artcreator
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: artcreator
          image: ghcr.io/kyma-incubator/kymart/artcreatorservice:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080